base_url = "https://sajadzarei.ir"

compile_sass = false

build_search_index = false


taxonomies = [
    {name = "type", feed = false}
  ]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
